apiVersion: v1
kind: Service
metadata:
  name: ficoscorecheckservice-deployment
  labels:
    app: ficoscorecheckservice
spec:
  type: LoadBalancer
  ports:
  - port: 8091
    name: http
  selector:
    app: ficoscorecheckservice
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ficoscorecheckservice-deployment
spec:
  replicas: 1 # just 1 pod
  template: 
    metadata:
      labels:
        app: ficoscorecheckservice
    spec:
      containers:
      - name: ficoscorecheckservice
        image: 8081386/ficoscorecheckservice
        ports:
        - containerPort: 8091