apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ficoscorecheckservice-deployment
spec:
  replicas: 1 # just 1 pod
  template: 
    metadata:
      labels:
        app: ficoscorecheckservice
    spec:
      containers:
      - name: ficoscorecheckservice
        image: mufgpoc/ficoscorecheckservice
        ports:
        - containerPort: 8091